# Generated by Django 4.1.5 on 2023-01-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.CharField(max_length=50)),
                ('period_to_receive_funds', models.CharField(max_length=50)),
                ('what_for', models.CharField(blank=True, max_length=50)),
                ('monthly_revenue', models.CharField(max_length=50)),
                ('credit_score', models.CharField(max_length=50)),
                ('period_in_business', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('bank_statement1', models.FileField(max_length=500, upload_to='documents')),
                ('bank_statement2', models.FileField(max_length=500, upload_to='documents')),
                ('bank_statement3', models.FileField(max_length=500, upload_to='documents')),
                ('business_legal_name', models.CharField(max_length=255)),
                ('business_dba_name', models.CharField(max_length=255)),
                ('industry_type', models.CharField(max_length=255)),
                ('gross_annual_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('use_of_proceeds', models.CharField(max_length=255)),
                ('federal_tax_id', models.CharField(max_length=255)),
                ('state_of_incorporation', models.CharField(max_length=255)),
                ('type_of_business_entity', models.CharField(max_length=255)),
                ('business_start_date', models.DateField(max_length=255)),
                ('merchant_email', models.EmailField(max_length=254)),
                ('open_cash_advance_or_loans', models.CharField(max_length=3)),
                ('open_bankruptcies', models.CharField(max_length=3)),
                ('tax_liens_or_judgements', models.CharField(max_length=3)),
                ('business_address', models.CharField(max_length=255)),
                ('business_city', models.CharField(max_length=255)),
                ('business_state', models.CharField(max_length=255)),
                ('business_zip', models.CharField(max_length=255)),
                ('physical_phone_number', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preferred_contact', models.CharField(max_length=255)),
                ('ss', models.CharField(max_length=255)),
                ('dob', models.DateField(max_length=255)),
                ('owner_address', models.CharField(max_length=255)),
                ('owner_city', models.CharField(max_length=255)),
                ('owner_state', models.CharField(max_length=255)),
                ('owner_zip', models.CharField(max_length=255)),
                ('ein_document', models.FileField(blank=True, max_length=500, null=True, upload_to='documents')),
                ('articles_of_incorporation', models.FileField(blank=True, max_length=500, null=True, upload_to='documents')),
                ('operating_agreement', models.FileField(blank=True, max_length=500, null=True, upload_to='documents')),
                ('business_license', models.FileField(blank=True, max_length=500, null=True, upload_to='documents')),
                ('insurance_document', models.FileField(blank=True, max_length=500, null=True, upload_to='documents')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Business_info',
            },
        ),
    ]
