# Generated by Django 4.1.5 on 2023-01-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_remove_loans_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loans',
            options={'verbose_name_plural': 'Loan'},
        ),
        migrations.AlterField(
            model_name='loans',
            name='gross_annual_sales',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loans',
            name='ownership_percentage',
            field=models.FloatField(),
        ),
    ]
