# Generated by Django 4.1.5 on 2023-02-03 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0003_alter_loans_options_alter_loans_gross_annual_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
