# Generated by Django 4.1.5 on 2023-02-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_loans_partner_1_loans_partner_2_loans_partner_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='partner_1_percantage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='partner_2_percantage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='partner_3_percantage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='partner_4_percantage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='partner_5_percantage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
